"""
This module contains the text descriptions for the symbols on the different 
classes of german traffic signs.
"""

descriptions = {
    0: "a two followed by a zero, representing the number twenty",
    1: "a three followed by a zero, representing the number thirty",
    2: "a five followed by a zero, representing the number fifty",
    3: "a six followed by a zero, representing the number sixty",
    4: "a seven followed by a zero, representing the number seventy",
    5: "an eight followed by a zero, representing the number eighty",
    6: "an eight followed by a zero, representing the number eighty, where the number is crossed out by four lines",
    7: "a one followed by two zeros, representing the number one hundred",
    8: "a one followed by a two followed by a zero, representing the number one hundred twenty",
    9: "two cars that are side-by-side viewed from behind; the left car is red and the right car is black",
    10: "a large truck on the left and a car on the right viewed from behind; the truck is red and the car is black",
    11: "a crossroad, with side roads to the left and to the right",
    12: "a square rotated ninety degrees to look like a diamond",
    13: "blank; nothing",
    14: "an S followed by a T followed by an O followed by a P, representing the word stop",
    15: "blank; nothing",
    16: "side view of a large truck that is facing toward the left",
    17: "a large dash",
    18: "a large exclamation point",
    19: "a curve that begins straight ahead and then turns to the left",
    20: "a curve that begins straight ahead and then turns to the right",
    21: "a curve that begins straight ahead, cuts back to the left, and then cuts back to continue straight ahead",
    22: "two bumps elevated from a flat surface",
    23: "a vehicle viewed from behind that is tilted to the right, with curvy tire marks trailing it",
    24: "two side-by-side lines; the left line is straight, while the right line begins parallel to the left line and then juts in closer to the left line toward the top",
    25: "a person bent over using a tool on a mound",
    26: "three circles stacked vertically with some space in between them; the top circle is red, the middle circle is yellow and the bottom circle is green",
    27: "a person viewed from the side who appears to be walking",
    28: "two people viewed from the side who appear to be running, the left person is smaller than the right person",
    29: "a bicycle viewed from the side, facing to the left",
    30: "a snowflake",
    31: "a deer viewed from the side that appears to be jumping, facing to the left",
    32: "blank space that is crossed out by four lines",
    33:  "an arrow that begins straight up and then turns to the right",
    34: "an arrow that begins straight up and then turns to the left",
    35: "an arrow that points straight up",
    36:  "an arrow that begins straight up, splits into one arrow pointing to the right and one arrow pointing straight up",
    37: "an arrow that begins straight up, splits into one arrow pointing to the left and one arrow pointing straight up",
    38: "a straight arrow that points down and to the right",
    39: "a straight arrow that points down and to the left",
    40: "three arrows arrange in a circle that are pointing counter clockwise",
    41: "two cars that are side-by-side viewed from behind; the cars are crossed out by four lines",
    42: "a large truck on the left and a car on the right viewed from behind; the vehicles are crossed out by four lines"
}